/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root";
import { Route as SettingsRouteImport } from "./routes/settings";
import { Route as IndexRouteImport } from "./routes/index";
import { Route as StoresIndexRouteImport } from "./routes/stores/index";
import { Route as ProductsIndexRouteImport } from "./routes/products/index";
import { Route as OrdersIndexRouteImport } from "./routes/orders/index";
import { Route as CollectionsIndexRouteImport } from "./routes/collections/index";
import { Route as CategoriesIndexRouteImport } from "./routes/categories/index";
import { Route as StoresNewRouteImport } from "./routes/stores/new";
import { Route as StoresStoreIdRouteImport } from "./routes/stores/$storeId";
import { Route as ProductsNewRouteImport } from "./routes/products/new";
import { Route as ProductsProductIdRouteImport } from "./routes/products/$productId";
import { Route as OrdersOrderIdRouteImport } from "./routes/orders/$orderId";
import { Route as CollectionsNewRouteImport } from "./routes/collections/new";
import { Route as CategoriesNewRouteImport } from "./routes/categories/new";
import { Route as AuthRegisterRouteImport } from "./routes/auth/register";
import { Route as AuthLoginRouteImport } from "./routes/auth/login";

const SettingsRoute = SettingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const StoresIndexRoute = StoresIndexRouteImport.update({
  id: "/stores/",
  path: "/stores/",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: "/products/",
  path: "/products/",
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersIndexRoute = OrdersIndexRouteImport.update({
  id: "/orders/",
  path: "/orders/",
  getParentRoute: () => rootRouteImport,
} as any);
const CollectionsIndexRoute = CollectionsIndexRouteImport.update({
  id: "/collections/",
  path: "/collections/",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: "/categories/",
  path: "/categories/",
  getParentRoute: () => rootRouteImport,
} as any);
const StoresNewRoute = StoresNewRouteImport.update({
  id: "/stores/new",
  path: "/stores/new",
  getParentRoute: () => rootRouteImport,
} as any);
const StoresStoreIdRoute = StoresStoreIdRouteImport.update({
  id: "/stores/$storeId",
  path: "/stores/$storeId",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsNewRoute = ProductsNewRouteImport.update({
  id: "/products/new",
  path: "/products/new",
  getParentRoute: () => rootRouteImport,
} as any);
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: "/products/$productId",
  path: "/products/$productId",
  getParentRoute: () => rootRouteImport,
} as any);
const OrdersOrderIdRoute = OrdersOrderIdRouteImport.update({
  id: "/orders/$orderId",
  path: "/orders/$orderId",
  getParentRoute: () => rootRouteImport,
} as any);
const CollectionsNewRoute = CollectionsNewRouteImport.update({
  id: "/collections/new",
  path: "/collections/new",
  getParentRoute: () => rootRouteImport,
} as any);
const CategoriesNewRoute = CategoriesNewRouteImport.update({
  id: "/categories/new",
  path: "/categories/new",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: "/auth/register",
  path: "/auth/register",
  getParentRoute: () => rootRouteImport,
} as any);
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: "/auth/login",
  path: "/auth/login",
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/categories/new": typeof CategoriesNewRoute;
  "/collections/new": typeof CollectionsNewRoute;
  "/orders/$orderId": typeof OrdersOrderIdRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
  "/stores/$storeId": typeof StoresStoreIdRoute;
  "/stores/new": typeof StoresNewRoute;
  "/categories/": typeof CategoriesIndexRoute;
  "/collections/": typeof CollectionsIndexRoute;
  "/orders/": typeof OrdersIndexRoute;
  "/products/": typeof ProductsIndexRoute;
  "/stores/": typeof StoresIndexRoute;
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/categories/new": typeof CategoriesNewRoute;
  "/collections/new": typeof CollectionsNewRoute;
  "/orders/$orderId": typeof OrdersOrderIdRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
  "/stores/$storeId": typeof StoresStoreIdRoute;
  "/stores/new": typeof StoresNewRoute;
  "/categories": typeof CategoriesIndexRoute;
  "/collections": typeof CollectionsIndexRoute;
  "/orders": typeof OrdersIndexRoute;
  "/products": typeof ProductsIndexRoute;
  "/stores": typeof StoresIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof IndexRoute;
  "/settings": typeof SettingsRoute;
  "/auth/login": typeof AuthLoginRoute;
  "/auth/register": typeof AuthRegisterRoute;
  "/categories/new": typeof CategoriesNewRoute;
  "/collections/new": typeof CollectionsNewRoute;
  "/orders/$orderId": typeof OrdersOrderIdRoute;
  "/products/$productId": typeof ProductsProductIdRoute;
  "/products/new": typeof ProductsNewRoute;
  "/stores/$storeId": typeof StoresStoreIdRoute;
  "/stores/new": typeof StoresNewRoute;
  "/categories/": typeof CategoriesIndexRoute;
  "/collections/": typeof CollectionsIndexRoute;
  "/orders/": typeof OrdersIndexRoute;
  "/products/": typeof ProductsIndexRoute;
  "/stores/": typeof StoresIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/settings"
    | "/auth/login"
    | "/auth/register"
    | "/categories/new"
    | "/collections/new"
    | "/orders/$orderId"
    | "/products/$productId"
    | "/products/new"
    | "/stores/$storeId"
    | "/stores/new"
    | "/categories/"
    | "/collections/"
    | "/orders/"
    | "/products/"
    | "/stores/";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/settings"
    | "/auth/login"
    | "/auth/register"
    | "/categories/new"
    | "/collections/new"
    | "/orders/$orderId"
    | "/products/$productId"
    | "/products/new"
    | "/stores/$storeId"
    | "/stores/new"
    | "/categories"
    | "/collections"
    | "/orders"
    | "/products"
    | "/stores";
  id:
    | "__root__"
    | "/"
    | "/settings"
    | "/auth/login"
    | "/auth/register"
    | "/categories/new"
    | "/collections/new"
    | "/orders/$orderId"
    | "/products/$productId"
    | "/products/new"
    | "/stores/$storeId"
    | "/stores/new"
    | "/categories/"
    | "/collections/"
    | "/orders/"
    | "/products/"
    | "/stores/";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  SettingsRoute: typeof SettingsRoute;
  AuthLoginRoute: typeof AuthLoginRoute;
  AuthRegisterRoute: typeof AuthRegisterRoute;
  CategoriesNewRoute: typeof CategoriesNewRoute;
  CollectionsNewRoute: typeof CollectionsNewRoute;
  OrdersOrderIdRoute: typeof OrdersOrderIdRoute;
  ProductsProductIdRoute: typeof ProductsProductIdRoute;
  ProductsNewRoute: typeof ProductsNewRoute;
  StoresStoreIdRoute: typeof StoresStoreIdRoute;
  StoresNewRoute: typeof StoresNewRoute;
  CategoriesIndexRoute: typeof CategoriesIndexRoute;
  CollectionsIndexRoute: typeof CollectionsIndexRoute;
  OrdersIndexRoute: typeof OrdersIndexRoute;
  ProductsIndexRoute: typeof ProductsIndexRoute;
  StoresIndexRoute: typeof StoresIndexRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof SettingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/stores/": {
      id: "/stores/";
      path: "/stores";
      fullPath: "/stores/";
      preLoaderRoute: typeof StoresIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/": {
      id: "/products/";
      path: "/products";
      fullPath: "/products/";
      preLoaderRoute: typeof ProductsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/orders/": {
      id: "/orders/";
      path: "/orders";
      fullPath: "/orders/";
      preLoaderRoute: typeof OrdersIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/collections/": {
      id: "/collections/";
      path: "/collections";
      fullPath: "/collections/";
      preLoaderRoute: typeof CollectionsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/categories/": {
      id: "/categories/";
      path: "/categories";
      fullPath: "/categories/";
      preLoaderRoute: typeof CategoriesIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/stores/new": {
      id: "/stores/new";
      path: "/stores/new";
      fullPath: "/stores/new";
      preLoaderRoute: typeof StoresNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/stores/$storeId": {
      id: "/stores/$storeId";
      path: "/stores/$storeId";
      fullPath: "/stores/$storeId";
      preLoaderRoute: typeof StoresStoreIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/new": {
      id: "/products/new";
      path: "/products/new";
      fullPath: "/products/new";
      preLoaderRoute: typeof ProductsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/products/$productId": {
      id: "/products/$productId";
      path: "/products/$productId";
      fullPath: "/products/$productId";
      preLoaderRoute: typeof ProductsProductIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/orders/$orderId": {
      id: "/orders/$orderId";
      path: "/orders/$orderId";
      fullPath: "/orders/$orderId";
      preLoaderRoute: typeof OrdersOrderIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/collections/new": {
      id: "/collections/new";
      path: "/collections/new";
      fullPath: "/collections/new";
      preLoaderRoute: typeof CollectionsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/categories/new": {
      id: "/categories/new";
      path: "/categories/new";
      fullPath: "/categories/new";
      preLoaderRoute: typeof CategoriesNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/register": {
      id: "/auth/register";
      path: "/auth/register";
      fullPath: "/auth/register";
      preLoaderRoute: typeof AuthRegisterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/auth/login": {
      id: "/auth/login";
      path: "/auth/login";
      fullPath: "/auth/login";
      preLoaderRoute: typeof AuthLoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SettingsRoute: SettingsRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  CategoriesNewRoute: CategoriesNewRoute,
  CollectionsNewRoute: CollectionsNewRoute,
  OrdersOrderIdRoute: OrdersOrderIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProductsNewRoute: ProductsNewRoute,
  StoresStoreIdRoute: StoresStoreIdRoute,
  StoresNewRoute: StoresNewRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  CollectionsIndexRoute: CollectionsIndexRoute,
  OrdersIndexRoute: OrdersIndexRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  StoresIndexRoute: StoresIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
