/**
 * StoreDurableObject - Per-store isolated SQLite database
 *
 * Each store gets its own Durable Object instance with a 10GB SQLite database.
 * All business data (products, orders, customers, etc.) is stored here.
 * Auth data (users, sessions) remains in global D1 for centralized management.
 *
 * Uses Drizzle ORM for type-safe queries.
 * Exposes service instances via RPC for Workers to call.
 */

import { drizzle, type DrizzleSqliteDODatabase } from "drizzle-orm/durable-sqlite";
import { migrate } from "drizzle-orm/durable-sqlite/migrator";
import * as schema from "./schema";
import {
  CartService,
  CategoryService,
  CollectionService,
  OrderService,
  ProductService,
} from "./services";

// Import migrations JSON (generated by drizzle-kit)
// Note: The migrations are bundled with the Worker
import { DurableObject } from "cloudflare:workers";
import migrations from "./migrations/migrations";

export class StoreDurableObject extends DurableObject<CloudflareBindings> {
  private db: DrizzleSqliteDODatabase<typeof schema>;
  private initialized: boolean = false;

  // Service instances (created once and reused)
  private productService: ProductService | null = null;
  private categoryService: CategoryService | null = null;
  private collectionService: CollectionService | null = null;
  private orderService: OrderService | null = null;
  private cartService: CartService | null = null;

  constructor(ctx: DurableObjectState, env: CloudflareBindings) {
    super(ctx, env);
    // Initialize Drizzle ORM with Durable Object's SQLite storage
    this.db = drizzle(ctx.storage, { schema, logger: false });

    // Run migrations on first access
    void ctx.blockConcurrencyWhile(async () => {
      if (!this.initialized) {
        await this.runMigrations();
        this.initialized = true;
      }
    });
  }

  /**
   * Run database migrations
   */
  private async runMigrations(): Promise<void> {
    try {
      await migrate(this.db, migrations);
    } catch (error) {
      console.error("Migration error:", error);
      // Schema might already exist from previous deployment
    }
  }

  // ====================
  // Service Accessors (RPC Methods)
  // ====================

  /**
   * Get Product Service instance for product operations
   *
   * Usage from Worker:
   * ```typescript
   * const stub = env.STORE_DO.get(env.STORE_DO.idFromName(storeId));
   * const productService = await stub.getProductService();
   * const products = await productService.list({ limit: 20, offset: 0 });
   * ```
   */
  async getProductService(): Promise<ProductService> {
    if (!this.productService) {
      this.productService = new ProductService(this.db);
    }
    return this.productService;
  }

  /**
   * Get Category Service instance for category operations
   */
  async getCategoryService(): Promise<CategoryService> {
    if (!this.categoryService) {
      this.categoryService = new CategoryService(this.db);
    }
    return this.categoryService;
  }

  /**
   * Get Collection Service instance for collection operations
   */
  async getCollectionService(): Promise<CollectionService> {
    if (!this.collectionService) {
      this.collectionService = new CollectionService(this.db);
    }
    return this.collectionService;
  }

  /**
   * Get Order Service instance for order operations
   */
  async getOrderService(): Promise<OrderService> {
    if (!this.orderService) {
      this.orderService = new OrderService(this.db);
    }
    return this.orderService;
  }

  /**
   * Get Cart Service instance for cart operations
   */
  async getCartService(): Promise<CartService> {
    if (!this.cartService) {
      this.cartService = new CartService(this.db);
    }
    return this.cartService;
  }

  // ====================
  // Utility Methods
  // ====================

  /**
   * Get the Drizzle database instance (for advanced queries)
   */
  async getDb(): Promise<DrizzleSqliteDODatabase<typeof schema>> {
    return this.db;
  }

  /**
   * Get default region (for storefront initialization)
   */
  async getDefaultRegion() {
    const region = await this.db.query.regions.findFirst({
      where: (regions, { and, eq, isNull }) =>
        and(eq(regions.id, "reg_default"), isNull(regions.deletedAt)),
    });
    return region ?? null;
  }

  /**
   * Health check - verify database is working
   */
  async healthCheck(): Promise<{ status: string; initialized: boolean }> {
    try {
      // Simple query to verify database is working
      await this.db.query.currencies.findFirst();
      return { status: "ok", initialized: this.initialized };
    } catch {
      return { status: "error", initialized: this.initialized };
    }
  }
}

// Export for Worker entry point
export { StoreDurableObject as default };
