/**
 * Global D1 Schema Index
 *
 * Only contains auth tables (Better Auth) and stores metadata.
 * All business tables (products, orders, customers, etc.) are in
 * per-store Durable Objects (see src/durable-objects/schema/).
 */

// Auth tables (generated by better-auth CLI)
export * from "./auth";

// Store metadata (links users to their Durable Object instances)
export * from "./store";
